version: '3.8'

services:
  hsw:
    image: hsw:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - db_network
      - web_network
    depends_on:
      - postgres
  nginx:
    image: nginx-hsw:latest
    container_name: "nginx"
    ports:
      - "80:80"
    networks:
      - web_network
    depends_on:
      - hsw
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hsw
    networks:
      - db_network

networks:
  db_network:
  web_network: