apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hsw-ingress
  annotations:
    nginx.ingress.kubernetes.io/load-balance: "least_time"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hsw-service
                port:
                  number: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hsw-service
  labels:
    app: hsw
spec:
  selector:
    app: hsw
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hsw-service-monitor
spec:
  selector:
    matchLabels:
      app: hsw
  endpoints:
    - port: http-traffic
      path: "/api/actuator/prometheus"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hsw
  template:
    metadata:
      labels:
        app: hsw
    spec:
      containers:
        - name: hsw
          image: hsw:0.7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
      initContainers:
        - name: init-container
          image: busybox:latest
          command:
            - sh
            - -c
            - >
              while ! nc -z postgres-service 5432; do
                echo "Waiting for postgres to become ready..."
                sleep 2
              done