server:
  servlet:
    context-path: /api

spring:
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: jdbc:postgresql://postgres:5432/hsw?currentSchema=public
    username: postgres
    password: 12345678
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        hbm2ddl:
          auto: update
        format_sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  task:
    scheduling:
      pool:
        size: 2

authProvider:
  github:
    login_url: https://github.com/login/oauth/access_token
    user_url: https://api.github.com/user
    redirect_uri: http://localhost/register