spring:
  datasource:
    username: hsw
    password: hsw

authProvider:
  github:
    redirect_uri: https://www.hackerupdates.com/register
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}