spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hsw?currentSchema=public
    username: postgres
    password: 12345678
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: localhost
      port: 6379