server:
  port: 3645
  servlet:
    context-path: /api

spring:
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/hsw?currentSchema=public
    username: postgres
    password: 12345678
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        hbm2ddl:
          auto: update
        format_sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  task:
    scheduling:
      pool:
        size: 2

authProvider:
  github:
    login_url: https://github.com/login/oauth/access_token
    user_url: https://api.github.com/user
    redirect_uri: http://www.localhost:8080/register


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: hsw
    password: hsw

authProvider:
  github:
    redirect_uri: https://www.hackerswork.com/register

---

spring:
  config:
    activate:
      on-profile: app-1
server:
  port: 3645

---

spring:
  config:
    activate:
      on-profile: app-2
server:
  port: 3646

---