server:
  servlet:
    context-path: /api

logging:
  level:
    com:
      hackerupdates: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: hsw
  data:
    redis:
      host: redis-service
      port: 6379
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: jdbc:postgresql://postgres-service:5432/hsw?currentSchema=public
    username: postgres
    password: 12345678
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        hbm2ddl:
          auto: update
        format_sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  task:
    scheduling:
      pool:
        size: 2

authProvider:
  github:
    login_url: https://github.com/login/oauth/access_token
    user_url: https://api.github.com/user
    redirect_uri: http://localhost/auth
    client_id: ${CLIENT_ID_FOR_LOCAL_ENV}
    client_secret: ${CLIENT_SECRET_FOR_LOCAL_ENV}